const mongoose = require('mongoose');

const storySchema = new mongoose.Schema({
  // Link the story to the user who created it
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // The URL of the image generated by Gemini/AI
  imageUrl: {
    type: String,
    required: true
  },
  // The original text prompt used for the generation
  prompt: {
    type: String,
    required: true
  },
  // Categorize the art style (Cartoon, Sketch, etc.)
  style: {
    type: String,
    enum: ['cartoon', 'sketch', 'storyboard', 'colorful'],
    default: 'cartoon'
  },
  // Metadata for the UI (Instagram-style "posted X hours ago")
  createdAt: {
    type: Date,
    default: Date.now,
    // Optional: Auto-delete story after 24 hours (86400 seconds)
    expires: 86400 
  }
});

// Create the model
const Story = mongoose.model('Story', storySchema);

module.exports = Story;